# Generated by Django 4.2.2 on 2023-07-02 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wake_up', models.TimeField()),
                ('coding_hours', models.CharField(max_length=100)),
                ('exercise', models.BooleanField()),
                ('remarks', models.CharField(max_length=1000000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
